### ISSUE TITLE
Red h1

### ISSUE THREAD

**Issue by edgarwe** [xanhtool/snap-style-vscode#4]
Hi,

I do no why but h1 have a color : red since y use your extension.

Look at the print screen :
![Capture d’écran 2020-01-23 à 14 21 37](https://user-images.githubusercontent.com/47147820/72987952-b0244f80-3deb-11ea-893e-1dcc608a2058.png)

This is not a big problem just not pleasant.
Thanks for all.

**Comment by hiepxanh** [comment]
sorry, is it working? I'm going to remove that stupid line on next release

**Comment by edgarwe** [comment]
Yes all is working just red :)

**Comment by hiepxanh** [comment]
oh my god, thank you so much, glad to here that someone told me that it working. I released new version and it is pending to review,please wait a few day. I will told you when it complete. Thank you so much to here that

**Comment by edgarwe** [comment]
Haha no problem, if you want some tips you can just have a look about this extension https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei it's to live reload on save but it also do the live css/sass.

**Comment by hiepxanh** [comment]
wow, that so wonderful, I will take a look into it and learn from them

**Comment by hiepxanh** [comment]
I just release 0.0.3 version that remove red h1, can you check in your free time?

**Comment by edgarwe** [comment]
Okay it work I just have some debug log in console on style edit.

**Comment by hiepxanh** [comment]
thank you, do you want me to turn it off?

**Comment by edgarwe** [comment]
You can keep it for developement but for production it's not pleasant.

**Comment by hiepxanh** [comment]
agree with that, I will remove that log on the next version. Can we close this issue?
